### ISSUE TITLE
[WonderSwan] Absolute Compatibility Checklist

### ISSUE THREAD

**Issue by asiekierka** [higan-emu/ares#908]
This is a list of most "known unknowns" on the road to maximizing Ares's WonderSwan core's cycle-level accuracy. They don't necessarily represent bugs - they can also describe areas which need further validation or research. They also, for the most part, don't affect the software library.

Issues marked with 🔹 are more likely to make for a "good first issue", if you'd like to try contributing to Ares...

- [ ] There's still a few bits in I/O ports for which intended (if any) purpose remains unknown:

## CPU/General SoC

- [ ] Pass all of [WSTimingTest](https://github.com/FluBBaOfWard/WSTimingTest). According to FluBBa, it is still receiving updates to cover more edge cases.
- [x] ~~Fix up most CPU opcode flag effects to match hardware.~~ -> See #912
- [ ] Fix division opcode (AAM, DIV, IDIV) flags and exception handling. This is apparently quite tricky: officially, the CPU flags changed are undefined.
- [x] ~~According to [WSMan](http://daifukkat.su/docs/wsman/), sprite DMA stalls the CPU. This has to be fixed in the WonderSwan core.~~ -> This is not correct! See #909 
  - [x] When does sprite DMA happen? -> Line 144, see #909 
- [ ] Implement open bus/unaligned I/O access quirks.
  - [ ] The WonderSwan distinguished between aligned I/O access (one word read) and unaligned I/O access (two word reads or two byte reads?). This is generally unimportant, except on ASWAN - the 0xB8-0xBF port range can only be read as words; trying to read the high byte as bytes returns open bus. This is fixed on SPHINX and SPHINX2.
  - [ ] ASWAN: Open bus is 0x0090 and present when bit 8 is set, or when I/O port address >= 0x0200 and (address & 0xFF) >= 0xB8, plus the quirk mentioned above.
  - [ ] SPHINX: Unknown
  - [ ] SPHINX2: (Requires confirmation) Same as ASWAN, but in mono mode open bus for addresses < 0x4000 is 0x0000, while in color mode it's 0x0000 for all addresses.
  * You can help! Download [ioports.zip](https://cdn.discordapp.com/attachments/804513374599512064/1009916615678242958/ioports.zip) and try it on *your* console!
- [x] ~~Implement memory wait states. More research required.~~ -> Initial implementation in #912
- [ ] Fully validate memory wait state behavior.
- [ ] On ASWAN, SRAM access has a mandatory 3-cycle wait state. ROM access speeds can be controlled via port 0xA0 between 1-cycle and 3-cycle. Does this also affect SRAM on Sphinx?

## PPU

- [ ] The WonderSwan Color's exact display timings are known thanks to zwenergy's research. How does the horizontal blanking period relate to image generation? (Pixel Accuracy mode only)
- [ ] The sprite table DMA runs during line 144. How do first/count I/O ports affect it? Does it always scan through the 256-word region, stalling until `i == first`, or does it start by reading the byte marked with `first`?

## APU

- [ ] Timing details are entirely unknown. As of Ares v131, they are broadly correct, but the exact RAM read and I/O port access timings within one sample remain unknown. (Pixel Accuracy mode only)
- [ ] Actually implement Hyper Voice.
  * Ares has a bare-bones implementation, but it doesn't support many of Hyper Voice's features.
  * See [STSWS](http://perfectkiosk.net/stsws.html#sound_hyper_voice) for a starting point.

## Miscellaneous

* ~~Actually implement the serial port.~~ Moved to https://github.com/ares-emulator/ares/issues/961
  * There is external PC software that can talk to a WonderSwan: WonderFence, for WonderGate peripheral emulation, as well as TransMagic and alternatives, for file transfer from/to WonderWitch.
  * It might be preferable to expose the serial port as a TCP socket. Mednafen uses an `excomm` configuration option, which calls an external program.
- [x] ~~Implement WonderWitch cartridge emulation.~~ https://github.com/ares-emulator/ares/pull/960
  - [ ] Implement proper NOR flash chip timings.
- [ ] Implement proper 2003<->RTC chip communication timings.
- [ ] Implement KARNAK (Pocket Challenge V2-exclusive mapper) ADPCM codec. Requires further hardware research.
- [ ] Add a checkbox for signaling low battery (triggers an NMI if enabled in port 0xB7), similar to the "Headphones" checkbox. 🔹
- [ ] Verify if the Key interrupt is edge- or level-triggered - [WSHWTest](https://github.com/FluBBaOfWard/WSHWTest) says level, but...
